In [1]:
import numpy as np

In [ ]:
# Task1 - Generate and insert Data

In [7]:
np.random.seed(42)

In [9]:
scores = np.random.randint(50,101, size = (5,4))
print("Original Scores Array:\n", scores)

Original Scores Array:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]


In [11]:
print("\n3rd student, 2nd student:", scores[2,1])


3rd student, 2nd student: 60


In [13]:
print("Last 2 students' scores:\n", scores[3:, :])

Last 2 students' scores:
 [[85 89 73 52]
 [71 51 73 93]]


In [15]:
print("First 3 students, subjects 2 & 3:\n", scores[0:3, 1:3])

First 3 students, subjects 2 & 3:
 [[78 64]
 [70 88]
 [60 60]]


In [ ]:
# Task2 - Analyze with Broadcasting

In [18]:
col_means = np.round(np.mean(scores, axis = 0), 2)
print("\nColumn-wise mean (subjects):", col_means)


Column-wise mean (subjects): [74.6 69.6 71.6 75.6]


In [20]:
curve = np.array([5,3,7,2])
curved_scores = scores + curve

In [22]:
curved_scores = np.minimum(curved_scores, 100)
print("Curved Scores (Max 100):\n", curved_scores)

Curved Scores (Max 100):
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]


In [24]:
row_maxes = np.max(curved_scores, axis = 1)
print("Best subject score per student:", row_maxes)

Best subject score per student: [94 95 77 92 95]


In [ ]:
# Task3 - Normalize and Identify

In [30]:
row_min = curved_scores.min(axis = 1, keepdims = True)
row_max = curved_scores.max(axis = 1, keepdims = True)
row_min

array([[71],
       [62],
       [63],
       [54],
       [54]])

In [32]:
row_max

array([[94],
       [95],
       [77],
       [92],
       [95]])

In [34]:
normalized_scores = (curved_scores - row_min) / (row_max - row_min)
print("\nNormalized Scores (0-1 scale):\n", normalized_scores)


Normalized Scores (0-1 scale):
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]


In [36]:
max_val = np.max(normalized_scores)
max_val

1.0

In [38]:
rows, cols = np.where(normalized_scores == max_val)
print(rows, cols)

[0 1 2 3 4] [3 2 0 1 3]


In [40]:
student_idx, subject_idx = rows[0], cols[0]
scores_above_90 = curved_scores[curved_scores > 90]
scores_above_90

array([93, 94, 95, 92, 95])

In [42]:
print("Normalized Scores:\n", np.round(normalized_scores, 2))
print(f"\nHighest Normalized Value Index: Student {student_idx}, Subject {subject_idx}")
print("Scores strictly above 90:", scores_above_90)

Normalized Scores:
 [[0.96 0.43 0.   1.  ]
 [0.   0.33 1.   0.24]
 [1.   0.   0.29 0.86]
 [0.95 1.   0.68 0.  ]
 [0.54 0.   0.63 1.  ]]

Highest Normalized Value Index: Student 0, Subject 3
Scores strictly above 90: [93 94 95 92 95]
